fullnameOverride: myapp
replicaCount: 1
image:
  repository: example/myapp-k8s
  tag: 1.0.0
  pullPolicy: Never
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: myapp.localtest.me
      paths:
        - path: /
          pathType: Prefix
